// @generated
// This file is @generated by prost-build.
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ScrollEvent {
    #[prost(enumeration = "ScrollSource", tag = "1")]
    pub source: i32,
    #[prost(double, tag = "2")]
    pub delta_x: f64,
    #[prost(double, tag = "3")]
    pub delta_y: f64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ClipboardEvent {
    #[prost(string, tag = "1")]
    pub client: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "2")]
    pub data: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Empty {
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ScrollSource {
    Wheel = 0,
    Finger = 1,
    Continuous = 2,
}
impl ScrollSource {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Wheel => "SCROLL_SOURCE_WHEEL",
            Self::Finger => "SCROLL_SOURCE_FINGER",
            Self::Continuous => "SCROLL_SOURCE_CONTINUOUS",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "SCROLL_SOURCE_WHEEL" => Some(Self::Wheel),
            "SCROLL_SOURCE_FINGER" => Some(Self::Finger),
            "SCROLL_SOURCE_CONTINUOUS" => Some(Self::Continuous),
            _ => None,
        }
    }
}
include!("synq.tonic.rs");
// @@protoc_insertion_point(module)
