// @generated
// This file is @generated by prost-build.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ScrollEvent {
    #[prost(int32, tag="1")]
    pub delta_x: i32,
    #[prost(int32, tag="2")]
    pub delta_y: i32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ClipboardEvent {
    #[prost(string, tag="1")]
    pub client: ::prost::alloc::string::String,
    #[prost(bytes="vec", tag="2")]
    pub data: ::prost::alloc::vec::Vec<u8>,
}
include!("synq.tonic.rs");
// @@protoc_insertion_point(module)
